#!/bin/sh
dir=/home/logical9/www/cgi-bin
ssh lp "cd $dir; tar cvf vblog.tar vblog"
ssh lp "cd $dir; tar cvf vbdbm.tar brigades"
scp lp:$dir/vb \
    lp:$dir/VB_SVG.pm \
    lp:/home/logical9/www/vb/help.html \
    lp:$dir/vblog.tar \
    lp:$dir/vbdbm.tar \
    .
